package com.islaharper.dawnofandroid.ui.theme

import androidx.compose.ui.unit.dp

val PADDING_SMALL = 6.dp
val PADDING_MEDIUM = 16.dp
val PADDING_LARGE = 20.dp
val PADDING_XLARGE = 40.dp

val PAGING_INDICATOR_WIDTH = 12.dp
val PAGING_INDICATOR_SPACING = 8.dp

val FLAVOUR_ITEM_HEIGHT = 400.dp

val NETWORK_ERROR_ICON_HEIGHT = 120.dp

val NAME_PLACEHOLDER_HEIGHT = 30.dp
val DESCRIPTION_PLACEHOLDER_HEIGHT = 15.dp
val RATING_PLACEHOLDER_HEIGHT = 20.dp

val TOP_BAR_HEIGHT = 56.dp
val MIN_SHEET_HEIGHT = 140.dp
val INFO_ICON_SIZE = 32.dp